export { default as Home } from "./Home";
export { default as Categories } from "./Categories";
export { default as Product } from "./Products";
export { default as About } from "./About";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Error } from "./ErrorPage";
export { default as Cart } from "./Cart";
export { default as Wishlist } from "./Wishlist";
